name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    publicRelease: "${{ github.ref == 'refs/heads/main' && 'True' || 'False' }}"
    configuration: "${{ github.ref == 'refs/heads/main' && 'Release' || 'Debug' }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2

    # Debug build
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration $configuration --no-restore -warnaserror
    - name: Test
      run: dotnet test --configuration $configuration --no-restore --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    # Release build
    - name: Install dependencies for release
      if: ${{ env.publicRelease }}
      run: dotnet restore
    - name: Build release
      if: ${{ env.publicRelease }}
      run: dotnet build --no-self-contained --configuration Release --no-restore -warnaserror
    - name: Package NuGet
      if: ${{ env.publicRelease }}
      run: dotnet pack --no-restore --no-build --configuration Release
    - name: Echo package version
      run: echo ${{ env.BUILD_VERSION }}
    - uses: actions/upload-artifact@v3
      if: ${{ env.publicRelease }}
      with:
        name: packages-drop
        path: |
          src/**/*.nupkg

  nuget-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      if: ${{ env.publicRelease }}
      with:
        name: packages-drop
    - name: Echo package version
      run: echo ${{ env.BUILD_VERSION }}
    - uses: actions/setup-dotnet@v1.7.2
      if: ${{ env.publicRelease }}
    - name: Publish NuGet Package
      run: dotnet nuget push Hic.Json.MSBuild.${{ env.BUILD_VERSION }}.nupkg -k secrets.NUGET_API_KEY

