name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2

    # Debug build
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug --no-restore -warnaserror
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    # Release build
    - name: Install dependencies for release
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet restore -r linux-musl-x64
    - name: Build release
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet build -r linux-musl-x64 --no-self-contained --configuration Release --no-restore -warnaserror
    - name: Publish release
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet publish --no-restore --no-build --configuration Release -r linux-musl-x64 --no-self-contained -p:PublishSingleFile=true
    - uses: actions/upload-artifact@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        name: build-drop
        path: |
          src/Web/bin/Release/net6.0/linux-musl-x64/
          src/Web/Dockerfile

  docker-release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'disabled' }}
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build-drop
    - uses: azure/docker-login@v1
      with:
        login-server: hicacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build . -t hicacr.azurecr.io/foreignaffairs:${{github.sha}} -t hicacr.azurecr.io/foreignaffairs:latest
        docker push hicacr.azurecr.io/foreignaffairs --all-tags
